# Generated by Django 3.0.4 on 2021-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('code', models.CharField(max_length=2, verbose_name='大类物料代号')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '物料编码大类',
            },
        ),
    ]
