# Generated by Django 3.0.4 on 2021-08-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_client_Interface_v1', '0002_auto_20210811_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc_info',
            options={'verbose_name': 'PC信息'},
        ),
        migrations.AlterField(
            model_name='pc_info',
            name='board_serialNumber',
            field=models.CharField(max_length=25, verbose_name='序列号'),
        ),
        migrations.CreateModel(
            name='disk_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=25, verbose_name='序列号')),
                ('size', models.CharField(max_length=25, verbose_name='容量')),
                ('_type', models.CharField(blank=True, default='Mechanics', max_length=25, null=True, verbose_name='类型')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_client_Interface_v1.Pc_info', verbose_name='电脑')),
            ],
            options={
                'verbose_name': '硬盘信息',
            },
        ),
    ]
