XXXX  XXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBBBBBBB
         XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XX
                BBB BBB BB BBBBBBBBBBBB
                    XXXXX XXXXXXX X XXXXXXXXXXXXXXXX
                BBBBBB
            XXXXXX
         XXXXXX
BBBBBB
         XXXXXX

