XXX XXXXXXXXXX XXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBB
        BB BBBBBBBBBBBBBBBBB BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB

    BBBBBB
XXXXX