# Generated by Django 3.0.4 on 2021-08-08 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Organizational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('parentid', models.CharField(blank=True, max_length=64, null=True, verbose_name='钉钉父部门ID')),
                ('dingID', models.CharField(blank=True, max_length=15, null=True, verbose_name='钉钉ID')),
                ('leader', models.ForeignKey(blank=True, help_text='部门领导', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='领导')),
            ],
            options={
                'verbose_name': '部门名称',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('url', models.CharField(max_length=256, verbose_name='含正则的URL')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='图标')),
                ('memu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Memu', verbose_name='所属一级菜单')),
                ('pid', models.ForeignKey(blank=True, help_text='不能成为二级菜单，但是要归属哪个二级菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='rbac.Permission', verbose_name='权限所性二级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('permission', models.ManyToManyField(blank=True, help_text='修改后需要重新登录才能生效', to='rbac.Permission', verbose_name='权限')),
                ('user', models.ManyToManyField(blank=True, help_text='包含用户', to=settings.AUTH_USER_MODEL, verbose_name='包含用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphome', models.CharField(blank=True, max_length=15, null=True, verbose_name='电话')),
                ('userSource', models.CharField(choices=[('0', '系统注册用户'), ('1', '钉钉用户'), ('2', '微信用户')], default='0', max_length=2, verbose_name='用户来源')),
                ('unionid', models.CharField(max_length=64, verbose_name='钉钉用户密码,unionid')),
                ('openid', models.CharField(blank=True, max_length=64, null=True, verbose_name='钉钉openid')),
                ('userid', models.CharField(default='0', help_text='userid该企业的唯一ID', max_length=64, verbose_name='钉钉dingId')),
                ('position', models.CharField(default='', help_text='职位信息', max_length=64, null=True, verbose_name='职位信息')),
                ('active', models.BooleanField(default=False, help_text='是否激活了钉钉', max_length=64, verbose_name='是否激活了钉钉')),
                ('avatar', models.CharField(blank=True, default='', help_text='钉钉头像url', max_length=256, null=True, verbose_name='头像url')),
                ('email', models.EmailField(blank=True, help_text='email', max_length=256, null=True, verbose_name='email')),
                ('nick', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('is_management', models.BooleanField(default=False, verbose_name='是否管理人员')),
                ('is_active', models.BooleanField(default=True, help_text='False是禁止登录', verbose_name='活跃')),
                ('organizational', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Organizational', verbose_name='部门')),
                ('role', models.ManyToManyField(to='rbac.Role', verbose_name='权限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
    ]
